### ISSUE TITLE
Difficulty using library

### ISSUE THREAD

**Issue by nubunto** [zhyu/nadia#1]
I started using the library just now, but I can't get pass this small issue:

    $ iex -S mix
    iex> Nadia.get_me
    ** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.128.0>,      #Reference<0.0.1.70>, {:client, :undefined, :hackney_dummy_metrics, :hackney_ssl_transport,     'api.telegram.org', 443, "api.telegram.org", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [],  :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
        ** (EXIT) no process
        (stdlib) gen_server.erl:212: :gen_server.call/3
                 src/hackney_client/hackney_manager.erl:66: :hackney_manager.init_request/1
                 src/hackney_client/hackney_manager.erl:56: :hackney_manager.new_request/1
                 src/hackney_connect/hackney_connect.erl:183: :hackney_connect.socket_from_pool/4
                 src/hackney_connect/hackney_connect.erl:36: :hackney_connect.connect/5
                 src/hackney_client/hackney.erl:321: :hackney.request/5
                 lib/httpoison.ex:60: HTTPoison.request/5
                 lib/nadia/api.ex:50: Nadia.API.request/3

  I'm using Elixir v1.0.5 and Nadia v0.3.1

**Comment by zhyu** [comment]
Try to modify your `mix.exs` like this:
```elixir
# 
  def application do
    [applications: [:nadia]]
  end
# ...
```

**Comment by nubunto** [comment]
It worked. Thanks!

**Comment by zhyu** [comment]
Thanks for reporting! I've updated the README.md.

**Comment by nubunto** [comment]
Awesome! Thanks for the help!
