### ISSUE TITLE
Recent code is not being loaded with 0.5.0

### ISSUE THREAD

**Issue by TheTharin** [zhyu/nadia#101]
Hi again! Newly added code that implemented Jason protocols for KeyboardMarkup (and several other structs) and the renaming of KeyboardHide  to KeyboardRemove is not being loaded with mix deps.get when the dependency is set to be ~> 0.5.0
I had to hack it in the deps myself for the bot to work.
Could you please update the release? Thanks in advance!!

**Comment by zhyu** [comment]
I published Nadia 0.6.0, which contains all those changes. So please use it instead of using 0.5.0.
Also, before a new version being published to hex.pm, you can just use the `master` branch of Nadia instead of using version, [ref|https://hexdocs.pm/mix/Mix.Tasks.Deps.html].
