### ISSUE TITLE
Error while loading project :nadia 

### ISSUE THREAD

**Issue by abdoo9** [zhyu/nadia#103]
first of all I'm new to elixir
I followed the instruction in readme but when I try to run the bot I got this error:
```
Error while loading project :nadia at /home/abdo/Desktop/tg-bots/nadia/deps/nadia
** (Mix) Trying to load Nadia.Mixfile from "/home/abdo/Desktop/tg-bots/nadia/deps/nadia/mix.exs" but another project with the same name was already defined at "/home/abdo/Desktop/tg-bots/nadia/mix.exs"     
```
note: I run the bot using this command: `sudo iex -S mix`

**Comment by NobbZ** [comment]
1. Don't run `sudo` unless you *know* you need it!
2. You can not name your app the same as one of your dependencies. You'll need to rename your app.
