### ISSUE TITLE
add support for downloading file

### ISSUE THREAD

**Issue by falood** [zhyu/nadia#11]
https://core.telegram.org/bots/api#getfile
Use `https://api.telegram.org/file/bot<token>/<file_path>` to get the file.

**Comment by zhyu** [comment]
IMO, handling the logic of file downloading in Nadia is not a good idea.
Maybe we could have a `get_file_link` method.

Anyway, pull requests are always welcome.

**Comment by anronin** [comment]
for example, what should `get_file_link` method do?

**Comment by anronin** [comment]
in search of other implementations I found `download_file` method. maybe i should implement it?

**Comment by zhyu** [comment]
nadia has `get_file_link/1` now since #16 has been merged.
I think it's enough in most cases, if there's still needs to have a `download_file` method, feel free to reopen this issue.
