### ISSUE TITLE
Option :offset to method #get_updates is unaffected

### ISSUE THREAD

**Issue by majioa** [zhyu/nadia#135]
Seems the option offset to method #get_updates is unaffected,

Since the code:
```
{:ok, updates} = Nadia.get_updates offset: 1, limit: 1
```
readout the same message as the:
```
{:ok, updates} = Nadia.get_updates limit: 1
```

**Comment by rockneurotiko** [comment]
`offset` is not how messages to skip, it's the ID of the first message you want to receive (you usually use it with last_message.id + 1):

https://core.telegram.org/bots/api#getupdates
