### ISSUE TITLE
Use keys: :atoms! to reuses existing atoms

### ISSUE THREAD

**Issue by anronin** [zhyu/nadia#18]
Why not use `keys: :atoms!` with the bang at the end of `:atoms!` in the `decode_response` function?
I understand that this is a very minor change, but it seems right) it can break something?
https://github.com/devinus/poison#parser
https://github.com/devinus/poison/issues/69

**Comment by anronin** [comment]
sorry, I see that it breaks down a lot, but it seemed to me that everything was working as before

**Comment by zhyu** [comment]
> Note that keys: :atoms! reuses existing atoms, i.e. if :name was not allocated before the call, you will encounter an argument error message.

https://github.com/devinus/poison#parser
