### ISSUE TITLE
Missing git tag

### ISSUE THREAD

**Issue by olgeni** [zhyu/nadia#28]
Hi,
Could you please add git tags for releases? It would make using git dependencies (and packaging) easier :)

**Comment by olgeni** [comment]
(ping?)

**Comment by zhyu** [comment]
I'm sorry for late response 😿 

I may add git tags in the future...
Please use commit SHA for now https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-git-options-git

**Comment by zhyu** [comment]
I release version 0.4.3 with tag: https://github.com/zhyu/nadia/releases/tag/v0.4.3

**Comment by olgeni** [comment]
Thanks a lot! 👍
