### ISSUE TITLE
Realtime updates?

### ISSUE THREAD

**Issue by cfenollosa** [zhyu/nadia#30]
Hi, is there any way to get the updates in real time or get notified instead of calling `Nadia.get_updates`?

Thanks!

**Comment by zhyu** [comment]
Check the document of webhook.

https://core.telegram.org/bots/api#setwebhook
Carlos Fenollosa <notifications@github.com>于2016年5月20日 周五18:50写道：

**Comment by cfenollosa** [comment]
If I understand it correctly, I need to implement an HTTP server to receive webhooks, right? It can't be done from inside Nadia?

Thanks!

**Comment by zhyu** [comment]
Yes, you should have a HTTP server if you want to use webhook.

Nadia is a wrapper of telegram bot api, so what you can do with Nadia is
the same as you use the raw telegram bot api.

If you don't want to implement a HTTP server, why not simply calling
get_updates every 5 seconds or whatever a time interval you like?

Carlos Fenollosa <notifications@github.com>于2016年5月20日 周五22:23写道：

**Comment by cfenollosa** [comment]
Thanks, I will try to connect the bot to a HTTP server.

I know the option to poll every X seconds is available, but I'd like to get realtime updates.
