### ISSUE TITLE
Add support for HTML5 Gaming Platform

### ISSUE THREAD

**Issue by optikfluffel** [zhyu/nadia#37]
Having support for the new [HTML5 Gaming Platform](https://core.telegram.org/bots/games) would be pretty cool. But before we start, we should probably close the other Issues und Pull Requests.

[Telegram Bot API - Games](https://core.telegram.org/bots/api#games)

**Comment by zhyu** [comment]
I agree, it's really cool!

But it seems not easy to test 😿 
I hope someone could help me...
