### ISSUE TITLE
Configurable API-Endpoint

### ISSUE THREAD

**Issue by steffkes** [zhyu/nadia#41]
Since i'm not only new to Elixir, but to Telegram as well - i was trying to proxy every request (inbound to my server as well as outbound to telegrams server). For their webhooks that worked pretty well, because you can put in every url you like as long as its https.

i wasn't able to make it work for/with Nadia, since the API-Endpoint is hardcoded in `lib/nadia/api.ex`.

i'm guessing that switching the API-Endpoint isn't a thing that is often done (completely understandable) but i still think it's a good idea to have that option. especially in the beginning when you start to make requests, it would be helpful if the requests could be send to any http endpoint .. so one would be able to verify what he/she is actually trying to send out :)

not yet sure about the tests for this, but the idea would probably be make it work the same way as `config_or_env` is already doing its job for the token.

I'll try to come up with a PR, depending on how much time there is .. somewhere in the next weeks.

WDYT @zhyu?

**Comment by zhyu** [comment]
Sorry for my late response.

I think it's a good idea, and it won't be so difficult to implement. As you mentioned, `config_or_env` will work for it too :)

Pull requests are always welcome :)
