### ISSUE TITLE
Support on new payments method.

### ISSUE THREAD

**Issue by aguxez** [zhyu/nadia#46]
Are there any plans on supporting the new Payment interace provided by Telegram?

**Comment by zhyu** [comment]
Thanks for asking :)

But the answer is no for the moment...
And I think it's not easy to test about it...

**Comment by icehaunter** [comment]
@zhyu About testing: it shouldn't be that much of a problem: https://core.telegram.org/bots/payments suggests a way to debug payments based bots without actually withdrawing any money, I could maybe try and tackle it, but it won't be fast, unfortunately

**Comment by roylez** [comment]
#139
