### ISSUE TITLE
Spec and function mismatch

### ISSUE THREAD

**Issue by icehaunter** [zhyu/nadia#67]
https://github.com/zhyu/nadia/blob/a78da4f4bcac2034974bc3781260ac80ae72672b/lib/nadia.ex#L578-L580

I think spec should be:
```elixir
  @spec edit_message_text(integer | binary, integer, binary, binary, [{atom, any}]) ::
          {:ok, Message.t()} | {:error, Error.t()}
  def edit_message_text(chat_id, message_id, inline_message_id, text, options \\ []) 
```

**Comment by m1ome** [comment]
Seems it may be closed: https://github.com/zhyu/nadia/blob/master/lib/nadia.ex#L591-L599
Issue fixed in code.
