### ISSUE TITLE
How to test code when using Nadia.

### ISSUE THREAD

**Issue by barthr** [zhyu/nadia#68]
I wan't to test code which calls `Nadia.get_updates()` How can I mock this Nadia instance to not rely on an external telegram chat?

I'm pretty new to elixir so I'm not really sure how to do this.

Greetings, Bart

**Comment by alexfilatov** [comment]
hey @barthr 

you can use https://github.com/jjh42/mock in your app to mock Nadia calls.
this would be like:

```
defmodule NadiaTest do
  use ExUnit.Case, async: false

  import Mock

  test "test nadia" do
    with_mock Nadia, [get_updates: fn() -> "_any_content_here_" end] do
      // put your test code here that makes calls to Nadia.get_updates()      
    end
  end
end
```

**Comment by barthr** [comment]
Wow! That looks really convenient, thanks!!
