### ISSUE TITLE
function :updates.__struct__/0 is undefined (module :updates is not available)

### ISSUE THREAD

**Issue by johannesE** [zhyu/nadia#71]
My application crashed because of this last night. I find it very weird, that it searches for an `:updates` module. Any idea what this could be? Sadly I don't have the message that produced this (if any).
```
** (UndefinedFunctionError) function :updates.__struct__/0 is undefined (module :updates is no
t available)
    :updates.__struct__()
    (elixir) lib/kernel.ex:1974: Kernel.struct/3
    (nadia) lib/nadia/api.ex:14: Nadia.API.process_response/2
    (databerg) lib/databerg/telegram/poller.ex:18: Databerg.Telegram.Poller.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :update}
```
In that line on [lib/nadia/api.ex:14](https://github.com/zhyu/nadia/blob/0b9b21e0cf8759d7882b97e323d32f4333f71b39/lib/nadia/api.ex#L14) it is calling the method `Nadia.Parser.parse_result/2` in which there is [this case line](https://github.com/zhyu/nadia/blob/0b9b21e0cf8759d7882b97e323d32f4333f71b39/lib/nadia/parser.ex#L34): `"getUpdates" -> parse(:updates, result)`. But how does that lead to this error? And if it does, why is this line not in the stack trace?

EDIT: Added a link to the parser.

**Comment by Voronchuk** [comment]
I have the same issue

**Comment by johannesE** [comment]
Thank you for the fix @Voronchuk.
