### ISSUE TITLE
support deleteWebhook and getWebhookInfo

### ISSUE THREAD

**Issue by zhyu** [zhyu/nadia#76]
* [`deleteWebhook`](https://core.telegram.org/bots/api#deletewebhook)
* [`getWebhookInfo`](https://core.telegram.org/bots/api#getwebhookinfo)

**Comment by konstantinzolotarev** [comment]
@zhyu Could we merge pr in here ?

**Comment by zhyu** [comment]
@konstantinzolotarev Sorry to keep you waiting. I merged p-r 🙇
