### ISSUE TITLE
Argument error with Nadia.API.build_url on Heroku

### ISSUE THREAD

**Issue by SukinoSenze** [zhyu/nadia#86]
### Problem
I try to build a Telegram webhook service running on Heroku.
I've received an incoming update via webhook and try to send a message back with Nadia.

Anyway, this error occurred with Nadia.send_message function on running service on Heroku.
I try to reproduce it by running an interactive shell and input with the same data but no error from the local test.

Are there any clues for it?

---

### Logging from Heroku Console
```
2019-05-06T15:40:28.289290+00:00 app[web.1]: ** (exit) an exception was raised:
2019-05-06T15:40:28.289292+00:00 app[web.1]:     ** (ArgumentError) argument error
2019-05-06T15:40:28.289294+00:00 app[web.1]:         :erlang.bit_size(nil)
2019-05-06T15:40:28.289296+00:00 app[web.1]:         (nadia) lib/nadia/api.ex:9: Nadia.API.build_url/1
2019-05-06T15:40:28.289297+00:00 app[web.1]:         (nadia) lib/nadia/api.ex:118: Nadia.API.request/3
```

**Comment by zhyu** [comment]
`Nadia.API.build_url` needs `base_url` and `token`.
Since `base_url` has a default value, I would like to suggest you checking your token configuration.

**Comment by m1ome** [comment]
@zhyu maybe it's a right way to throw error on empty token?

**Comment by zhyu** [comment]
@m1ome you're right. It's good to have a error message for that.

However, currently `build_url` will be called every time `Nadia` makes a request to telegram server, adding token check there means it'll be checked every time too :(
If we're going to add this check, it should be done when application starts up.
And `Nadia` may support multiple bot as many people requested, which need to change token related parts too.

Considering it's not an error occurs frequently, I tend to not prioritize this task.

**Comment by SukinoSenze** [comment]
Oh, I have checked and it might be caused by a missing `token` that @zhyu mentioned.
(that's my mistake on a production config)

Anyway, I think having a better error message would be great :)

Thank you all for spending time with my issue.
