### ISSUE TITLE
Unable to use Nadia in Mix.Tasks

### ISSUE THREAD

**Issue by holyxiaoxin** [zhyu/nadia#9]
Right now, I'm on able to use Nadia in `iex -S mix`. 

However, I would like to run it as a task. But with the same command of `Nadia.send_message(_)`, I'm getting some errors:

```
** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.172.0>, #Reference<0.0.2.124>, {:client, :undefined, :hackney_dummy_metrics, :hackney_ssl_transport, 'api.telegram.org', 443, "api.telegram.org", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
             src/hackney_manager.erl:66: :hackney_manager.init_request/1
             src/hackney_manager.erl:56: :hackney_manager.new_request/1
             src/socket/hackney_connect.erl:183: :hackney_connect.socket_from_pool/4
             src/socket/hackney_connect.erl:36: :hackney_connect.connect/5
             src/hackney.erl:321: :hackney.request/5
             lib/httpoison/base.ex:395: HTTPoison.Base.request/9
             lib/nadia/api.ex:58: Nadia.API.request/3
```

I'm wondering if there are any dependencies/default task being called by Nadia that I'm not including in my task?

**Comment by zhyu** [comment]
How do you run nadia in a task? Could you show me the definition of the task and the contents of `mix.exs`?

**Comment by holyxiaoxin** [comment]
`lib/Mix/Tasks/bot.run.ex`

```
defmodule Mix.Tasks.Bot.Run do
    IO.puts "Starting task...."
    IO.inspect Nadia.get_me
end
```

Outputs >>
```
Starting task...
** (exit) exited in: :gen_server.call(:hackney_manager, {:new_request, #PID<0.47.0>, #Reference<0.0.3.164>, {:client, :undefined, :hackney_dummy_metrics, :hackney_ssl_transport, 'api.telegram.org', 443, "api.telegram.org", [], nil, nil, nil, true, :hackney_pool, 5000, false, 5, false, 5, nil, nil, nil, :undefined, :start, nil, :normal, false, false, false, :undefined, false, nil, :waiting, nil, 4096, "", [], :undefined, nil, nil, nil, nil, :undefined, nil}}, :infinity)
    ** (EXIT) no process
    (stdlib) gen_server.erl:212: :gen_server.call/3
    src/hackney_manager.erl:66: :hackney_manager.init_request/1
    src/hackney_manager.erl:56: :hackney_manager.new_request/1
    src/socket/hackney_connect.erl:183: :hackney_connect.socket_from_pool/4
    src/socket/hackney_connect.erl:36: :hackney_connect.connect/5
    src/hackney.erl:321: :hackney.request/5
    lib/httpoison/base.ex:395: HTTPoison.Base.request/9
    lib/nadia/api.ex:58: Nadia.API.request/3
```

**Comment by zhyu** [comment]
ok, I got it.

you want to use Nadia in a task, but the dependencies(in this case, `hackney`) are not up.

please try this:
```elixir
defmodule Mix.Tasks.Bot do
  use Mix.Task

  def run(_) do
    Mix.Task.run "app.start", []
    IO.inspect Nadia.get_me
  end
end
```

**Comment by holyxiaoxin** [comment]
I'll try that later. thanks. (:

Any idea why I need to do `Mix.Task.run "app.start"`? I can't seem to find any tasks/ dependencies in `deps/nadia/lib` or `deps/nadia/mix.exs`.

I'm wondering if this scenario is specific to your library or with every library that I'm using.

Thanks for the clarification, I'm still figuring out how applications are run in the elixir world. I come from ruby. (:

**Comment by zhyu** [comment]
well, `Nadia` uses `HTTPosion`(which uses `hackney`) to send HTTP requests.
so you need to ensure `HTTPoison` is up to send requests.

For normal usage(not in task, like `iex -S mix`), you need to start `Nadia` like this:
```elixir
def application do
  [applications: [:nadia]]
end
```
https://github.com/zhyu/nadia#configuration

and `Nadia` will start its dependencies(`HTTPoison`), https://github.com/zhyu/nadia/blob/master/mix.exs#L18-L20

and `HTTPoison` will start its dependencies, and so on.


so, whatever library you use, if it do need to start the process, you should start it first.

Anyway, I don't think use `Nadia` in task is a good idea, if you want to build a cli project, try [elixir script](http://elixir-lang.org/getting-started/modules.html#scripted-mode).
Mix itself is a elixir script. https://github.com/elixir-lang/elixir/tree/master/lib/mix

**Comment by holyxiaoxin** [comment]
I've tested it. It works fine. You're right. Thanks for the headstart! (:

**Comment by techgaun** [comment]
@holyxiaoxin btw, if you still want to use on mix task, I've been able to do something like below:
```
Application.ensure_all_started(:nadia)
```

**Comment by holyxiaoxin** [comment]
@techgaun great point. just saw it in `http://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html`
