### ISSUE TITLE
protocol Jason.Encoder not implemented for %Nadia.Model.InlineKeyboardMarkup

### ISSUE THREAD

**Issue by astorre88** [zhyu/nadia#90]
We have an error `protocol Jason.Encoder not implemented for %Nadia.Model.InlineKeyboardMarkup` after upgrade from Poison to Jason

**Comment by astorre88** [comment]
Oh, sorry, I've checked this issue https://github.com/zhyu/nadia/pull/89. So, it's better to merge it))

**Comment by zhyu** [comment]
Hi @astorre88, I merged #89. Hope it'll work for you :)

**Comment by astorre88** [comment]
Hi! Thank you!

**Comment by astorre88** [comment]
A problem has been solved))

**Comment by MassiveFermion** [comment]
I'm getting this error!
